config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
  end
  resources :posts
  root "posts#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy

  def show
    @user = User.find(params[:id])
  end
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/concerns/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation)
  end
  def account_update_params
    params.require(:user).permit(:name, :username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def search
    if params[:search].blank?
      redirect_to('/posts/index', alert: "Please enter a valid search term") and return
    else
      @paramateer = params[:search].downcase
      @results = Article.all.where("lower(name LIKE, :search", search: "%#{@paramateer}%")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:post)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Books4change</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag  "https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"%>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="notification is-primary global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <%end %>
    <% if flash[:alert] %>
      <div class="notification is-danger global-notification">
        <p class="alert"><%= alert %></p>
      </div>
  <% end %>
    <nav class = "navbar is-primary">
      <div class="navbar-brand">
      <%= link_to root_path, class: "navbar-item" do %>
          <img src="http://www.jlteran.com/myemagination/assets/img/openbooklogo.png">
          <p class ="title is-4">Books4Change </p>
      <% end %>
        <div class="navbar-item has-dropdown is-hoverable has-text-">
          <a class="navbar-link has-text-black">
            More
          </a>

          <div class="navbar-dropdown">
            <a class="navbar-item" <%= link_to "About us" , page_path("about") %> </a>
            <a class="navbar-item" <%= link_to "Contact" , page_path("contact") %> </a>
            <hr class="navbar-divider">
            <a class="navbar-item" <%= link_to "Report An Issue" , page_path("report") %> </a>
          </div>
        </div>
      </div>

      <div class="navbar-burger burger" data-target="navbarExample">
          <span></span>
          <span></span>
          <span></span>
        </div>
      </div>

      <div id="navbarExample" class="navbar-menu">
        <div class="navbar-end">
          <div class="field is-grouped">
            <p class="control">
              <%= link_to 'All Authors', users_path, class: "button is-primary is-inverted has-text-black" %>

            </p>
            <% if user_signed_in? %>
              <p class="control">
                <%= link_to 'New Post', root_path, class: "button is-primary is-inverted has-text-black" %>

              </p>
            <p class="control">
              <%= link_to current_user.name, edit_user_registration_path, class:"button is-pramary has-text-black" %>
            </p>
              <p>
              <%=link_to "Logout", destroy_user_session_path, method: :delete, class:"button is-primary has-text-black"%>
              </p>
              <% else %>
            <p class ="control">
              <%= link_to 'Sign In', new_user_session_path, class: "button is-primary" %>
            </p>
              <p class = "control">
                <%= link_to 'Sign Up', new_user_registration_path, class: "button is-info" %>
              </p>
              <% end %>
          </div>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>

  <footer class="footer">
    <div class="content has-text-centered">
      <p>
        <strong>Books4Change</strong> by <a href="https://github.com/brokentimemachine">Adham Elbaz</a>. The source code is licensed
        <a href="http://opensource.org/licenses/mit-license.php">MIT</a>. The website content
        is licensed. Copyright CSC415 2018 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY NC SA 4.0</a>.
      </p>
    </div>
  </footer>
</html>

app/views/pages/about.html.erb
<section class="hero is-light is-medium">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        About Us
      </h1>
      <h2 class="subtitle">
        Mission Statement. Our Vision. And More.
      </h2>
      <p class="is-large">Books4Change is a not for profit open source platform connecting
      multicultural children's literature authors with active publishers who are looking
      for new content.</p>
      <p class="is-small">Our mission is to create a world where all children
      can see themselves through the pages of books.</p>
    </div>
  </div>
</section>

app/views/pages/contact.html.erb
<section class="hero is-light is-medium">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Contact
      </h1>
      <h2 class="subtitle">
        Your comments, questions, and concerns matter to us. Reach out to us
        and we'll get back to you ASAP.
      </h2>
      <p> Reach us by email: info@books4change.com</p>
      <p> Reach us by phone: 201-212-2222</p>
    </div>
  </div>
</section>

app/views/pages/report.html.erb
<section class="hero is-light is-medium">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Report an Issue
      </h1>
      <h2 class="subtitle">
        We're sorry you're having trouble. Let us know what the issue is
        by submitting the form below or submit an issue on github! You can also attach
        a screenshot below.
      </h2>
      <div class="field">
        <div class="control">
          <textarea class="textarea is-primary" placeholder="Tell us the problem you're having"></textarea>
        </div>
      </div>
      <div class="file">
        <label class="file-label">
          <input class="file-input" type="file" name="resume">
          <span class="file-cta">
      <span class="file-icon">
        <i class="fas fa-upload"></i>
      </span>
      <span class="file-label">
        Choose a file…
      </span>
    </span>
        </label>
      </div>
      <%= link_to 'Submit', root_path, class:"button is-primary" , notice: "Report Submitted Sucessfully" %>
      <%= link_to 'Cancel', root_path, class:"button is-inverted" , notice: "Report Submitted Sucessfully" %>
    </div>
  </div>

</section>

app/views/posts/_feed.html.erb
<div class="column is-half">
  <% if user_signed_in? %>
  <article class="media box">
    <figure class="media-left">
      <p class = "image is-64x64">
        <% gravatar_image_tag(current_user.email, size:65, alt: current_user.name) %>
      </p>
    </figure>
    <div class="media-content">
      <%= render 'posts/form' %>
    </div>
  </article>
<% end %>
<% @posts.each do | post |  %>
  <div class="box">
    <article class="media">
      <div class="media-left">
        <figure class="image is 64x64">
          <%= gravatar_image_tag(post.user.email, size: 64, alt: post.user.name)%>
        </figure>
      </div>
      <div class="media-content">
        <div class="content">
          <strong><%= post.user.name %></strong><br />
          <small><%= link_to post.user.username, users_path%></small>
          <p> <%= post.post  %></p>
        </div>
        <% if user_signed_in? && current_user == post.user  %>
        <nav class="level">
          <div class="level-left is-mobile">
            <%= link_to post, class: "level-item" do %>
              <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                  <% end %>
            <%= link_to edit_post_path(post), class:"level-item" do %>
            <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
              <% end %>
            <%= link_to post, method: :delete, data: { confirm: "are you sure you want to delete this post?"
            } do %>
              <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i> </span>
              <% end %>
          </div>
        </nav>
        <% end %>
      </div>
    </article>
  </div>
<% end %>
</div>

app/views/posts/_form.html.erb
<%= simple_form_for(@post) do |f| %>
  <%= f.error_notification %>
  <div class="field">
    <div class="control">
      <%= f.input :post, label: "Post about it", input_html: { class: "textarea "}, wrapper: false,
                  label_html: {class: "label"}, placeholder: "Compose a new post...", autofocus: true %>
    </div>
  </div>
  <%= f.button :submit, class: "button is-primary" %>
<% end %>

app/views/posts/_profile.html.erb
<div class="column is-one-quarter">
  <nav class="panel">
    <p class="panel-heading">Profile</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-64x64">
            <%= gravatar_image_tag(current_user.email, size: 64, alt: current_user.name) %>
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong><%= current_user.name %></strong><br />
              <small><%= current_user.username %></small><br>
              <%= link_to "See Profile", current_user %>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <div class="level is-mobile">
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Posts</p>
            <p class="title is-6"><%= current_user.posts.count %></p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Following</p>
            <p class="title is-6">123</p>
          </div>
        </div>
        <div class="level-item has-centered-text">
          <div>
            <p class="heading">Collabs</p>
            <p class="title is-6">18</p>
          </div>
        </div>
      </div>
    </div>
  </nav>
</div>

app/views/posts/_who-to-collab.html.erb
<div class="column">
  <nav class="panel">
    <p class="panel-heading">Who to Collab With</p>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>John Smith</strong>
              <small> @johnsmith</small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>Ashley Matos</strong>
              <small> @ashmatos</small>
            </p>
          </div>
        </div>
      </article>
    </div>
    <div class="panel-block">
      <article class="media">
        <div class="media-left">
          <figure class="image is-32x32">
            <img src="https://bulma.io/images/placeholders/64x64.png">
          </figure>
        </div>
        <div class="media-content">
          <div class="content">
            <p>
              <strong>Vrajkumar Deep</strong>
              <small>@vrajdeep1</small>
            </p>
          </div>
        </div>
      </article>
    </div>
  </nav>
</div>

app/views/posts/edit.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Editing Tweeet</h1>
        <%= render 'form', post: @post %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', posts_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
  </div>
</nav>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<section class="section">
  <div class="container">
    <div class="columns">
      <% if user_signed_in? %>
        <%= render 'profile' %>
        <% end %>
      <%= render 'feed' %>
      <%= render 'who-to-collab' %>
    </div>
  </div>
</section>

app/views/posts/new.html.erb
<div class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-half">
        <h1 class="title">Create a new Tweeet</h1>
        <%= render 'form', post: @posts %>
      </div>
    </div>
  </div>
</div>

<nav class="navbar is-fixed-bottom">
  <div class="navbar-menu">
    <div class="navbar-item">
      <div class="field is-grouped">
        <p class="control">
          <%= link_to 'Cancel', posts_path, class: "button is-dark" %>
        </p>
      </div>
    </div>
</nav>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/users/index.html.erb
<h1 class="title is-1">All Authors</h1>

<% @users.each do |user| %>
  <div class="tile is-parent ">
    <article class="tile is-child notification is-primary is-rounded has-text-black has-text-weight-bold is-size-5">
       <p><%= user.username %></p>
      <p>Member Since : <%= user.created_at %></p>
      <p><%= gravatar_image_tag(user.email, size:65, alt: user.name) %></p>
    </article>
  </div>
<% end %>

app/views/users/show.html.erb
<% if user_signed_in? %>
<div class="tile is-parent">
  <article class="tile is-child notification is-primary-is-inverted is-rounded">
    <p class="title"> <%= current_user.name %> </p>
    <p class="subtitle"><%= current_user.username %></p>
    <p class="subtitle"><%= current_user.email %></p>
    <p class="subtitle"><%= current_user.publications %></p>
<!--    <li class="round-image-50"><%#= image_tag(current_user.avatar.url(:thumb)) %></li>-->
<% end %>
</article>
</div>
<% current_user.posts.each do | post |  %>
    <div class="tile is-parent">
      <div class="tile is-child box">
        <div class="content">
          <p> <%= post.post  %><br>
            Post Created At :<%= post.created_at  %></p><br>
             <% if user_signed_in? && current_user == post.user  %>
            <nav class="level">
              <div class="level-left is-mobile">
                <%= link_to post, class: "level-item" do %>
                  <span class="icon"><i class="fa fa-link" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to edit_post_path(post),class:"level-item" do %>
                  <span class="icon"><i class="fa fa-pencil" aria-hidden="true"></i></span>
                <% end %>
                <%= link_to post, method: :delete, data: { confirm: "are you sure you want to delete this post?"
                } do %>
                  <span class="icon"><i class="fa fa-trash-o" aria-hidden="true"></i> </span>
                <% end %>
              </div>
            </nav>
            </div>
            </div>
      </div>
  <% end %>
<% end %>